### ISSUE TITLE
What the state of this project?

### ISSUE THREAD

**Issue by Avi-D-coder** [ecstatic-morse/const-phf#1]
Does it work, how is the runtime per?

**Comment by ecstatic-morse** [comment]
It works so feel free to fork, but it's just a proof-of-concept. Runtime perf should be faster than `rust-phf`, since we do a brute force search through a much simpler class of hash functions than the compress-hash-displace family used by `rust-phf`. Compile-time is exponential in the number of keywords, however.

**Comment by Avi-D-coder** [comment]
Can you think of a reason why it wouldn't  be possible to const build a union of two `PhfMap`s?
